from keyboards.client_keyboard import client_menu_kb
from keyboards.admin_keyboard import admin_menu_kb, add_product_kd
from keyboards.admin_inline_buttons import cancel_input_inline_kd, product_editor_menu_inline_kd
